name: Publish Website
on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Configure AWS Credentials and upload
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read-write
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-2'   
        SOURCE_DIR: './'
    - name: invalidate
      uses: awact/cloudfront-action@master
      env:
        DISTRIBUTION_ID: E16Y3YUTP2AQMX 
        PATHS: '/*'
        AWS_REGION: 'eu-west-2'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
